import assert from "node:assert/strict";
import test from "node:test";
import { scoutCase } from "../lib/server/evidence-scout";
import { runInvestigationFlow } from "../lib/server/investigation-flow";
import type { InvestigationMemoryStore } from "../lib/server/memory-store";
import { readFileSync } from "node:fs";
import { POST } from "../app/api/investigate/route";
const gbpCase = JSON.parse(readFileSync(new URL("../examples/gbp-rub-june-2023.json", import.meta.url), "utf8"));
test("GBP/RUB scout returns versioned official-source fixtures through the catalog", async () => { const { request, scout } = await scoutCase(gbpCase); assert.equal(request.evidence.length, 7); assert.equal(scout.human_evidence.length, 0); assert.ok(scout.retrieved_evidence.every((e) => e.origin === "sherlock_retrieval" && e.source_url.startsWith("https://") && e.verification_status === "fixture_pending_live_verification")); });
test("Scout evidence reaches investigation flow as retrieval context", async () => { const { request, scout } = await scoutCase(gbpCase); const snapshot = JSON.parse(readFileSync(new URL("../examples/case-b.expected-investigation.json", import.meta.url), "utf8")); let context: unknown; const store: InvestigationMemoryStore = { findPrecedents: async () => [], save: async () => {} }; const result = await runInvestigationFlow({ ...request, iteration: 1 }, store, async (input) => { context = (input as { retrieved_evidence_context?: unknown }).retrieved_evidence_context; return { ok: true, investigation: snapshot, rawResponses: [] }; }, scout); assert.equal(result.ok, true); assert.equal((context as unknown[]).length, 7); });
test("real API handler recognizes the GBP/RUB Scout fixture before normal request validation", async () => { const response = await POST(new Request("http://localhost/api/investigate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(gbpCase) }) as never); assert.notEqual(response.status, 400); });
