export type InvestigationType = "causal" | "diagnostic" | "comparative" | "predictive" | "descriptive";
export type EpistemicStatus = "sufficient_evidence" | "insufficient_evidence";
export type HypothesisAssessment = "unsupported" | "plausible" | "supported" | "weakened" | "refuted";
export type ObservationStatus = "observed" | "expected_but_absent" | "unexpected_observed" | "not_checked" | "unobservable";
export type CausalChainStatus = "observed" | "expected_but_absent" | "not_checked" | "unobservable" | "occurred_but_ineffective" | "unknown_due_to_telemetry_gap";
export interface CausalChainStep { step_id: string; prerequisite_step: string | null; expected_event: string; expected_effect: string; relevant_time_window: string; evidence_of_execution: string | null; evidence_of_effect: string | null; detection_opportunity: string; observation_status: CausalChainStatus; actual_observation: string | null; consequence_of_absence: string; downstream_impact: string; }
export interface CausalHypothesis { id: string; causal_claim: string; proposed_cause: string; affected_outcome: string; mechanism: string; scope: string; relevant_time_window: string; discriminating_prediction_ids: string[]; causal_chain: CausalChainStep[]; first_problematic_step_id: string | null; falsifier: string; next_discriminating_test: string; impact_if_found: string; assessment: HypothesisAssessment; }
export interface PredictionRecord { id: string; hypothesis_id: string; expected_observation: string; causal_link: string; target_variable: string; expected_direction: string; entity_or_population: string; relevant_time_window: string; observation_source: string; detection_opportunity: string; detection_coverage: string; observation_status: ObservationStatus; actual_observation: string | null; evidential_consequence: string; explanation: string; }
export interface EvidenceHypothesisLink { evidence_id: string; hypothesis_id: string; prediction_id: string; relation: "supports" | "weakens" | "contradicts" | "neutral" | "not_discriminating"; explanation: string; independence_group: string; limitations: string; }
export interface SherlockInvestigationV2 { schema_version: "2.0.0"; original_question: string; investigation_type: InvestigationType; observed_phenomenon: string; phenomenon_validation: string; baseline: string | null; anomaly_status: "not_observed" | "observed" | "anomaly_not_established" | "anomaly_established"; causal_hypotheses: CausalHypothesis[]; predictions: PredictionRecord[]; evidence: unknown[]; evidence_links: EvidenceHypothesisLink[]; unexplained_observations: string[]; epistemic_status: EpistemicStatus; leading_hypothesis: string | null; missing_evidence: string[]; next_discriminating_tests: string[]; semantic_audit: { passed: boolean; issues: string[]; repair_attempts: number }; }
